### ISSUE TITLE
Syslog input keeps dying with the message "An existing connection was forcibly closed by the remote host"

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-input-syslog#11]
(This issue was originally filed by @ilyalozovyy at https://github.com/elastic/logstash/issues/2104)

---

Running on Windows 2008 R2 with Java 8u25
Getting the following stack trace:

←[33msyslog udp listener died {:address=>"0.0.0.0:514", :exception=>#<SocketError: recvfrom: name or service not known>,
 :backtrace=>["D:/Apps/logstash/lib/logstash/inputs/syslog.rb:119:in `udp_listener'", "org/jruby/RubyKernel.java:1521:in
 `loop'", "D:/Apps/logstash/lib/logstash/inputs/syslog.rb:118:in `udp_listener'", "D:/Apps/logstash/lib/logstash/inputs/
syslog.rb:76:in `run'"], :level=>:warn, :file=>"/Apps/logstash/lib/logstash/inputs/syslog.rb", :line=>"80"}←[0m

The configuration that I am using is:

input { 
	syslog {
		type => "syslog"
		port => 514
	}
	tcp {
		type => "web"
		port => 10000
		codec => "json"
	}
	tcp {
		type => "eventlog"
		port => 10001
		codec => "json"
	}
}

output {
	if [type] == "syslog" {
		stdout {
			codec => rubydebug
		}
	}
}

Any ideas what could be causing this failure?

**Comment by Wurzelmann** [comment]
I'm getting this as well:

    {:timestamp=>"2015-06-15T11:54:24.265000+0200", :message=>"syslog listener died", :protocol=>:udp, :address=>"0.0.0.0:5517", :exception=>#<SocketError: recvfrom: name or service not known>, :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-syslog-0.1.6/lib/logstash/inputs/syslog.rb:138:in `udp_listener'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-syslog-0.1.6/lib/logstash/inputs/syslog.rb:117:in `server'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-syslog-0.1.6/lib/logstash/inputs/syslog.rb:97:in `run'"], :level=>:warn}

My config:

    input {
      syslog {
        host => "0.0.0.0"
        type => "switches"
        port => 5517
      }
    }

Additional note: I'm using multiple syslog inputs simultanously because of different log types.

**Comment by Wurzelmann** [comment]
Update: I replaced all my simultanous syslog inputs with "tcp" inputs, but to no avail:

{:timestamp=>"2015-06-18T09:48:47.541000+0200", :message=>"An error occurred. Closing connection", :client=>"172.27.10.131:39532", :exception=>#<SystemCallError: Unknown error - Die Verbindung wurde vom Kommunikationspartner zurÃ¼ckgesetzt>, :backtrace=>["org/jruby/RubyIO.java:3018:in `sysread'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-0.1.5/lib/logstash/inputs/tcp.rb:164:in `read'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-0.1.5/lib/logstash/inputs/tcp.rb:112:in `handle_socket'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-0.1.5/lib/logstash/inputs/tcp.rb:147:in `client_thread'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-0.1.5/lib/logstash/inputs/tcp.rb:145:in `client_thread'"], :level=>:error}

**Comment by Wurzelmann** [comment]
Okay, maybe this helps:

I changed a line in the syslog input gem file (/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-syslog-0.1.6/lib/logstash/inputs/syslog.rb in my case). There's a part, where the TCP listener is defined:

    def tcp_listener(output_queue)
    @logger.info("Starting syslog tcp listener", :address => "#{@host}:#{@port}")
    @tcp = TCPServer.new(@host, @port)

    loop do
      socket = @tcp.accept
      @tcp_sockets << socket

      break if @shutdown_requested.true?

      Thread.new(output_queue, socket) do |output_queue, socket|
        tcp_receiver(output_queue, socket)
      end 
    end 
  ensure
    close_tcp
      end # def tcp_listener

I replaced "
    break if @shutdown_requested.true?"
with 

    " break if @shutdown_requested.false?" and logstash hasn't crashed since then. This was three days ago, normally logstash would crash after a few hours at the latest. It is a dirty hack, but it seems to work...
