### ISSUE TITLE
Test randomly failing when testing all the plugins on jenkins

### ISSUE THREAD

**Issue by ph** [logstash-plugins/logstash-input-syslog#7]
```
Failures:

  1) inputs/syslog should properly handle locale and timezone inputs
     Failure/Error: Unable to find matching line from backtrace
     IOError:
       closed stream
     # org/jruby/RubyIO.java:3535:in `each'
     # /home/jenkins/workspace/Logstash_1.5_All_Plugins_test/vendor/bundle/jruby/1.9/gems/logstash-input-syslog-0.1.3/lib/logstash/inputs/syslog.rb:175:in `tcp_receiver'
     # /home/jenkins/workspace/Logstash_1.5_All_Plugins_test/vendor/bundle/jruby/1.9/gems/logstash-input-syslog-0.1.3/lib/logstash/inputs/syslog.rb:161:in `tcp_listener'

Finished in 2 minutes 5 seconds
604 examples, 1 failure
```

**Comment by purbon** [comment]
related to #6
